.PHONY: all gh-pages sf-files

.SUFFIXES:

all: gh-pages sf-files

GH_NAME = Oliver Schmidt
GH_MAIL = ol.sc@web.de
GH_PATH = ../doc

gh-pages:

SF_USER = oliverschmidt
SF_HOST = frs.sourceforge.net
SF_FILE = /home/frs/project/cc65/cc65-snapshot-win32.zip

SCPFLAGS = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q

sf-files:
