name: Snapshot Build
on:
  push:
    branches:
      master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - shell: bash
        run: git config --global core.autocrlf input

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app (debug)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Debug

      - name: Build app (release)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Release

    # enter secrets under "repository secrets"
          
      # TODO: Update docs at https://github.com/cc65/doc
      # TODO: Publish snapshot zip at https://github.com/cc65/cc65.github.io
