name: Windows Test Manual
# Manually dispatched because it's much slower than the Linux test.

on:
  workflow_dispatch:

jobs:
  build_windows:
    name: Build, Test (Windows MSVC)
    runs-on: windows-latest

    steps:
      - name: Git Setup
        shell: bash
        run: git config --global core.autocrlf input

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app (MSVC debug)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Debug

      - name: Build app (MSVC release)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Release

      - name: Build utils (MinGW)
        shell: cmd
        run: make -j2 util

      - name: Build the platform libraries (make lib)
        shell: cmd
        run: make -j2 lib QUIET=1

      - name: Run the regression tests (make test)
        shell: cmd
        run: make test QUIET=1

      - name: Test that the samples can be built (make samples)
        shell: cmd
        run: make -j2 samples
